package Project;

import javax.swing.JOptionPane;

public class ForgetPassword extends javax.swing.JFrame {

    Database db = new Database();
    public ForgetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base1 = new javax.swing.JPanel();
        Right1 = new javax.swing.JPanel();
        Logo1 = new javax.swing.JLabel();
        LogoName1 = new javax.swing.JLabel();
        Left1 = new javax.swing.JPanel();
        Forget = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        PasswordText = new javax.swing.JPasswordField();
        Update = new java.awt.Button();
        Login = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgotten Pasoword");
        setPreferredSize(new java.awt.Dimension(1366, 768));

        Base1.setPreferredSize(new java.awt.Dimension(1366, 768));
        Base1.setLayout(null);

        Right1.setBackground(new java.awt.Color(0, 102, 102));
        Right1.setPreferredSize(new java.awt.Dimension(633, 768));

        Logo1.setForeground(new java.awt.Color(0, 102, 102));
        Logo1.setIcon(new javax.swing.ImageIcon("E:\\Coding\\MedicalStockManagement\\logo\\logo.jpg")); // NOI18N

        LogoName1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        LogoName1.setForeground(new java.awt.Color(255, 255, 255));
        LogoName1.setText("Vandana Nursing Home");

        javax.swing.GroupLayout Right1Layout = new javax.swing.GroupLayout(Right1);
        Right1.setLayout(Right1Layout);
        Right1Layout.setHorizontalGroup(
            Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right1Layout.createSequentialGroup()
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Right1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(LogoName1))
                    .addGroup(Right1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(Logo1)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        Right1Layout.setVerticalGroup(
            Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right1Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(Logo1)
                .addGap(54, 54, 54)
                .addComponent(LogoName1)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        Base1.add(Right1);
        Right1.setBounds(0, 0, 633, 768);

        Left1.setBackground(new java.awt.Color(255, 255, 255));
        Left1.setPreferredSize(new java.awt.Dimension(633, 768));

        Forget.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Forget.setForeground(new java.awt.Color(0, 102, 102));
        Forget.setText("Forget Password");

        Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email.setText("Email");

        EmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextActionPerformed(evt);
            }
        });

        Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Password.setText("New Password");

        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });

        Update.setActionCommand("Login");
        Update.setBackground(new java.awt.Color(0, 102, 102));
        Update.setForeground(new java.awt.Color(153, 255, 255));
        Update.setLabel("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Login.setActionCommand("Login");
        Login.setBackground(new java.awt.Color(255, 204, 204));
        Login.setLabel("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Left1Layout = new javax.swing.GroupLayout(Left1);
        Left1.setLayout(Left1Layout);
        Left1Layout.setHorizontalGroup(
            Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Left1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Left1Layout.createSequentialGroup()
                        .addGroup(Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Left1Layout.createSequentialGroup()
                        .addGroup(Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(315, 315, 315))))
            .addGroup(Left1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(Forget)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        Left1Layout.setVerticalGroup(
            Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Left1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(Forget)
                .addGap(78, 78, 78)
                .addComponent(Email)
                .addGap(18, 18, 18)
                .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password)
                .addGap(18, 18, 18)
                .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        Base1.add(Left1);
        Left1.setBounds(630, 0, 740, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Base1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Base1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextActionPerformed

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here
        String email = EmailText.getText(); // The email should be the unique identifier
        String password = PasswordText.getText(); // New password

        if (db.UpdateInfo(email, password)) {
            JOptionPane.showMessageDialog(null, "Password updated successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Error updating password");
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LoginActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base1;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel Forget;
    private javax.swing.JPanel Left1;
    private java.awt.Button Login;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel LogoName1;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JPanel Right1;
    private java.awt.Button Update;
    // End of variables declaration//GEN-END:variables
}
